name: ci con node.js

on:
  pull_request:
    branches: [master]

jobs: 
  ci_to_master:
    runs-on: windows-server
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
       with:
        node-versionn: 10
      - run: npm ci
      - run: npm install
      - run: npm run build
      - run: npm start